"""
PyInstaller hook for Pygments to minimize executable size.

This hook explicitly includes only the Pygments lexers needed for common
documentation languages. All other lexer modules are excluded.

Supported languages: Python, JavaScript, TypeScript, Bash, JSON, YAML, 
HTML, CSS, SQL, Java, Go, Rust, C, C++, Markdown, Diff, INI, TOML
"""

# Include only the lexer modules that are explicitly imported in converter.py
# Plus all their transitive dependencies
hiddenimports = [
    # Core Pygments - required for basic operation
    'pygments',
    'pygments.lexers',
    'pygments.lexers.special',  # Required by Pygments __init__.py
    'pygments.formatters',
    'pygments.formatters.html',
    'pygments.styles',
    'pygments.styles.default',
    'pygments.token',
    'pygments.util',
    'pygments.filter',
    'pygments.filters',
    'pygments.regexopt',
    'pygments.plugin',
    'pygments.scanner',
    'pygments.lexinfo',
    
    # Core lexer base classes (required by all lexers)
    'pygments.lexer',
    
    # Explicitly included lexer modules (common documentation languages)
    'pygments.lexers.python',
    'pygments.lexers.javascript',  # Includes TypeScript
    'pygments.lexers.shell',
    'pygments.lexers.data',  # JSON, YAML
    'pygments.lexers.html',
    'pygments.lexers.ruby',  # Required by html.py
    'pygments.lexers.css',
    'pygments.lexers.sql',
    'pygments.lexers.jvm',  # Java, Kotlin, Scala
    'pygments.lexers.go',
    'pygments.lexers.rust',
    'pygments.lexers.c_cpp',
    'pygments.lexers.markup',
    'pygments.lexers.lilypond',  # Required by markup.py
    'pygments.lexers.lisp',  # Required by lilypond.py
    'pygments.lexers.diff',
    'pygments.lexers.configs',  # INI, TOML, etc.
    'pygments.lexers.text',
    'pygments.lexers.textedit',
    'pygments.lexers.mime',
    
    # Additional dependencies for markup.py
    'pygments.lexers.python',  # Already included
]

# Exclude all other lexer modules to reduce executable size
# These are lexers for specialized/rarely-used languages
excludedimports = [
    'pygments.lexers.actionscript',
    'pygments.lexers.adl',
    'pygments.lexers.agile',
    'pygments.lexers.algol',
    'pygments.lexers.ambient',
    'pygments.lexers.amdgpu',
    'pygments.lexers.ampl',
    'pygments.lexers.apdlexer',
    'pygments.lexers.antlr',
    'pygments.lexers.aos',
    'pygments.lexers.apl',
    'pygments.lexers.archetype',
    'pygments.lexers.arrow',
    'pygments.lexers.arturo',
    'pygments.lexers.asc',
    'pygments.lexers.asm',
    'pygments.lexers.asn1',
    'pygments.lexers.automation',
    'pygments.lexers.bare',
    'pygments.lexers.basic',
    'pygments.lexers.bdd',
    'pygments.lexers.berry',
    'pygments.lexers.bibtex',
    'pygments.lexers.blueprint',
    'pygments.lexers.boa',
    'pygments.lexers.bqn',
    'pygments.lexers.business',
    'pygments.lexers.c_like',
    'pygments.lexers.capnproto',
    'pygments.lexers.carbon',
    'pygments.lexers.cddl',
    'pygments.lexers.chapel',
    'pygments.lexers.clean',
    'pygments.lexers.comal',
    'pygments.lexers.compiled',
    'pygments.lexers.cpl',
    'pygments.lexers.crystal',
    'pygments.lexers.csound',
    'pygments.lexers.d',
    'pygments.lexers.dalvik',
    'pygments.lexers.devicetree',
    'pygments.lexers.dylan',
    'pygments.lexers.ecl',
    'pygments.lexers.eiffel',
    'pygments.lexers.elm',
    'pygments.lexers.elpi',
    'pygments.lexers.emacs',
    'pygments.lexers.erlang',
    'pygments.lexers.esoteric',
    'pygments.lexers.ezhil',
    'pygments.lexers.factor',
    'pygments.lexers.fantom',
    'pygments.lexers.felix',
    'pygments.lexers.fift',
    'pygments.lexers.floscript',
    'pygments.lexers.fortran',
    'pygments.lexers.foxpro',
    'pygments.lexers.freefem',
    'pygments.lexers.func',
    'pygments.lexers.functional',
    'pygments.lexers.futhark',
    'pygments.lexers.gcodelexer',
    'pygments.lexers.gdscript',
    'pygments.lexers.grammar_notation',
    'pygments.lexers.graph',
    'pygments.lexers.graphics',
    'pygments.lexers.graphql',
    'pygments.lexers.haskell',
    'pygments.lexers.haxe',
    'pygments.lexers.hdl',
    'pygments.lexers.hexdump',
    'pygments.lexers.hyper',
    'pygments.lexers.igor',
    'pygments.lexers.inferno',
    'pygments.lexers.installers',
    'pygments.lexers.int_fiction',
    'pygments.lexers.iolang',
    'pygments.lexers.j',
    'pygments.lexers.julia',
    'pygments.lexers.kuin',
    'pygments.lexers.macaulay2',
    'pygments.lexers.make',
    'pygments.lexers.mason',
    'pygments.lexers.math',
    'pygments.lexers.matlab',
    'pygments.lexers.maxima',
    'pygments.lexers.ml',
    'pygments.lexers.modeling',
    'pygments.lexers.modula2',
    'pygments.lexers.mojo',
    'pygments.lexers.monte',
    'pygments.lexers.mosel',
    'pygments.lexers.ncl',
    'pygments.lexers.nimrod',
    'pygments.lexers.nit',
    'pygments.lexers.nix',
    'pygments.lexers.oberon',
    'pygments.lexers.objective',
    'pygments.lexers.ooc',
    'pygments.lexers.other',
    'pygments.lexers.parasail',
    'pygments.lexers.parsers',
    'pygments.lexers.pascal',
    'pygments.lexers.pawn',
    'pygments.lexers.perl',
    'pygments.lexers.php',
    'pygments.lexers.pointless',
    'pygments.lexers.pony',
    'pygments.lexers.praat',
    'pygments.lexers.procfile',
    'pygments.lexers.prolog',
    'pygments.lexers.promela',
    'pygments.lexers.prt',
    'pygments.lexers.ptx',
    'pygments.lexers.q',
    'pygments.lexers.qlik',
    'pygments.lexers.qvt',
    'pygments.lexers.r',
    'pygments.lexers.rdf',
    'pygments.lexers.rebol',
    'pygments.lexers.resource',
    'pygments.lexers.ride',
    'pygments.lexers.rita',
    'pygments.lexers.rnc',
    'pygments.lexers.roboconf',
    'pygments.lexers.robot',
    'pygments.lexers.ruby',  # Keep - required by html.py
    'pygments.lexers.sas',
    'pygments.lexers.savi',
    'pygments.lexers.scd',
    'pygments.lexers.scdoc',
    'pygments.lexers.scripting',
    'pygments.lexers.sgf',
    'pygments.lexers.slash',
    'pygments.lexers.smalltalk',
    'pygments.lexers.smithy',
    'pygments.lexers.smv',
    'pygments.lexers.snobol',
    'pygments.lexers.solidity',
    'pygments.lexers.sophia',
    'pygments.lexers.spice',
    'pygments.lexers.stata',
    'pygments.lexers.supercollider',
    'pygments.lexers.swift',
    'pygments.lexers.tact',
    'pygments.lexers.tcl',
    'pygments.lexers.teal',
    'pygments.lexers.templates',
    'pygments.lexers.teraterm',
    'pygments.lexers.testing',
    'pygments.lexers.tex',
    'pygments.lexers.theorem',
    'pygments.lexers.thingsdb',
    'pygments.lexers.tlb',
    'pygments.lexers.tnt',
    'pygments.lexers.trafficscript',
    'pygments.lexers.typoscript',
    'pygments.lexers.typst',
    'pygments.lexers.ul4',
    'pygments.lexers.unicon',
    'pygments.lexers.urbi',
    'pygments.lexers.usd',
    'pygments.lexers.varnish',
    'pygments.lexers.verification',
    'pygments.lexers.verifpal',
    'pygments.lexers.vip',
    'pygments.lexers.webidl',
    'pygments.lexers.webmisc',
    'pygments.lexers.wgsl',
    'pygments.lexers.whiley',
    'pygments.lexers.x10',
    'pygments.lexers.xorg',
    'pygments.lexers.yang',
    'pygments.lexers.yara',
    'pygments.lexers.zig',
    'pygments.lexers.idl',
    'pygments.lexers.phix',
    
    # Other Pygments modules not needed for basic operation
    'pygments.cmdline',
    'pygments.console',
    'pygments.formatters.latex',
    'pygments.formatters.other',
    'pygments.formatters.pangomarkup',
    'pygments.formatters.rtf',
    'pygments.formatters.svg',
    'pygments.formatters.terminal',
    'pygments.formatters.terminal256',
    'pygments.guess',
]
